In [1]:
import pandas as pd

dataset = pd.read_csv("/Users/cristinaabrahamse/Documents/Eduvos University/Data Science Honours /Early Prediction of Burnout (Honours Proj.)/Burnout Datasets (Raw)/mental_health_workplace_survey.csv")

In [2]:
dataset.head(10)

,EmployeeID,Age,Gender,Country,JobRole,Department,YearsAtCompany,WorkHoursPerWeek,RemoteWork,BurnoutLevel,...,CommuteTime,HasMentalHealthSupport,ManagerSupportScore,HasTherapyAccess,MentalHealthDaysOff,SalaryRange,WorkLifeBalanceScore,TeamSize,CareerGrowthScore,BurnoutRisk
0,1001,50,Male,UK,Sales Associate,HR,14,47,No,3.37,...,117,No,3.15,Yes,8,40K-60K,8.82,6,9.20,0
1,1002,36,Male,Germany,Software Engineer,IT,1,59,Hybrid,7.39,...,8,Yes,4.40,Yes,4,80K-100K,2.80,45,8.46,1
2,1003,29,Non-binary,India,IT Admin,IT,13,59,Hybrid,7.10,...,75,No,3.63,No,6,80K-100K,7.28,7,7.96,1
3,1004,42,Male,Australia,HR Specialist,IT,15,31,Yes,4.18,...,43,Yes,4.50,Yes,9,60K-80K,1.31,11,8.90,0
4,1005,40,Male,Brazil,Customer Support,Support,6,34,Yes,8.28,...,58,Yes,5.51,Yes,6,<40K,1.17,18,8.88,1
5,1006,44,Prefer not to say,Germany,Project Manager,Support,3,58,Hybrid,3.12,...,23,Yes,2.56,No,6,40K-60K,5.06,38,4.32,0
6,1007,32,Prefer not to say,USA,Software Engineer,Engineering,17,30,Hybrid,5.15,...,62,No,4.54,Yes,9,100K+,6.91,12,9.76,0
7,1008,32,Male,Canada,Customer Support,Marketing,4,39,No,5.25,...,77,Yes,4.47,No,3,80K-100K,2.28,22,7.38,0
8,1009,45,Prefer not to say,Canada,Marketing Manager,Sales,5,49,Hybrid,4.07,...,112,No,3.57,No,3,80K-100K,7.87,3,4.33,0
9,1010,57,Prefer not to say,Brazil,Software Engineer,Engineering,6,59,Hybrid,9.59,...,40,Yes,9.99,No,2,60K-80K,2.16,19,4.98,1

In [3]:
dataset.shape

(3000, 25)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EmployeeID              3000 non-null   int64
 1   Age                     3000 non-null   int64
 2   Gender                  3000 non-null   object
 3   Country                 3000 non-null   object
 4   JobRole                 3000 non-null   object
 5   Department              3000 non-null   object
 6   YearsAtCompany          3000 non-null   int64
 7   WorkHoursPerWeek        3000 non-null   int64
 8   RemoteWork              3000 non-null   object
 9   BurnoutLevel            3000 non-null   float64
 10  JobSatisfaction         3000 non-null   float64
 11  StressLevel             3000 non-null   float64
 12  ProductivityScore       3000 non-null   float64
 13  SleepHours              3000 non-null   float64
 14  PhysicalActivityHrs     3000 non-null   float64
 15  CommuteTime             3000 non-null   int64
 16  HasMentalHealthSupport  3000 non-null   object
 17  ManagerSupportScore     3000 non-null   float64
 18  HasTherapyAccess        3000 non-null   object
 19  MentalHealthDaysOff     3000 non-null   int64
 20  SalaryRange             3000 non-null   object
 21  WorkLifeBalanceScore    3000 non-null   float64
 22  TeamSize                3000 non-null   int64
 23  CareerGrowthScore       3000 non-null   float64
 24  BurnoutRisk             3000 non-null   int64
dtypes: float64(9), int64(8), object(8)
memory usage: 586.1+ KB

In [5]:
dataset.isnull().sum().sort_values(ascending=False)

EmployeeID                0
SleepHours                0
CareerGrowthScore         0
TeamSize                  0
WorkLifeBalanceScore      0
SalaryRange               0
MentalHealthDaysOff       0
HasTherapyAccess          0
ManagerSupportScore       0
HasMentalHealthSupport    0
CommuteTime               0
PhysicalActivityHrs       0
ProductivityScore         0
Age                       0
StressLevel               0
JobSatisfaction           0
BurnoutLevel              0
RemoteWork                0
WorkHoursPerWeek          0
YearsAtCompany            0
Department                0
JobRole                   0
Country                   0
Gender                    0
BurnoutRisk               0
dtype: int64

In [6]:
dataset.duplicated().sum()

np.int64(0)

In [7]:
dataset.describe(include="all")

,EmployeeID,Age,Gender,Country,JobRole,Department,YearsAtCompany,WorkHoursPerWeek,RemoteWork,BurnoutLevel,...,CommuteTime,HasMentalHealthSupport,ManagerSupportScore,HasTherapyAccess,MentalHealthDaysOff,SalaryRange,WorkLifeBalanceScore,TeamSize,CareerGrowthScore,BurnoutRisk
count,3000.000000,3000.000000,3000,3000,3000,3000,3000.000000,3000.000000,3000,3000.000000,...,3000.000000,3000,3000.00000,3000,3000.000000,3000,3000.000000,3000.00000,3000.000000,3000.000000
unique,NaN,NaN,4,7,8,6,NaN,NaN,3,NaN,...,NaN,2,NaN,2,NaN,5,NaN,NaN,NaN,NaN
top,NaN,NaN,Non-binary,India,Data Scientist,HR,NaN,NaN,Hybrid,NaN,...,NaN,No,NaN,No,NaN,100K+,NaN,NaN,NaN,NaN
freq,NaN,NaN,757,464,411,525,NaN,NaN,1022,NaN,...,NaN,1531,NaN,1511,NaN,640,NaN,NaN,NaN,NaN
mean,2500.500000,40.805667,NaN,NaN,NaN,NaN,10.099333,44.504000,NaN,5.509137,...,59.227000,NaN,5.44254,NaN,4.544667,NaN,5.450950,25.20100,5.520680,0.326667
std,866.169729,11.011705,NaN,NaN,NaN,NaN,6.035032,8.491526,NaN,2.574072,...,34.809779,NaN,2.59740,NaN,2.854129,NaN,2.602379,14.08645,2.566861,0.469072
min,1001.000000,22.000000,NaN,NaN,NaN,NaN,0.000000,30.000000,NaN,1.000000,...,0.000000,NaN,1.00000,NaN,0.000000,NaN,1.000000,1.00000,1.000000,0.000000
25%,1750.750000,31.000000,NaN,NaN,NaN,NaN,5.000000,37.000000,NaN,3.300000,...,29.000000,NaN,3.16000,NaN,2.000000,NaN,3.160000,13.00000,3.300000,0.000000
50%,2500.500000,41.000000,NaN,NaN,NaN,NaN,10.000000,45.000000,NaN,5.480000,...,59.000000,NaN,5.44000,NaN,5.000000,NaN,5.425000,25.00000,5.580000,0.000000
75%,3250.250000,50.000000,NaN,NaN,NaN,NaN,15.000000,52.000000,NaN,7.640000,...,90.000000,NaN,7.69000,NaN,7.000000,NaN,7.730000,37.00000,7.642500,1.000000
max,4000.000000,59.000000,NaN,NaN,NaN,NaN,20.000000,59.000000,NaN,10.000000,...,119.000000,NaN,9.99000,NaN,9.000000,NaN,10.000000,49.00000,9.990000,1.000000

Dataset Evaluation – Synthetic Workplace Burnout Dataset
Original Purpose

This dataset appears to have been created to simulate workplace conditions and burnout-related factors for machine learning and data analysis purposes. It contains numerous workplace variables commonly associated with occupational burnout.

Strengths
Includes a wide range of workplace-related variables relevant to occupational burnout, such as:
Work-life balance
Weekly working hours
Manager support
Remote work
Department
Years at company
Mental health days
Therapy access
Salary range
Burnout level
Burnout risk
The variables are well structured and suitable for machine learning modelling.
Requires relatively little preprocessing because the variables are already organised and labelled.
Limitations

The dataset appears to be synthetically generated rather than collected from real employees.

As a result:

the relationships between variables are simulated rather than observed,
the burnout risk and burnout level variables are artificially generated,
the dataset does not reflect authentic workplace experiences or employee responses.

Since this study aims to analyse real-world secondary datasets representing working individuals, the use of synthetic data would not align with the methodological approach described in the research proposal.

Alignment with Research Aim

Although the variables closely match the concepts investigated in this study, the dataset does not satisfy the requirement for analysing real employee data. Consequently, it would not provide evidence that reflects actual workplace burnout experiences.

Preliminary Decision

Rejected as a primary research dataset.

However, the dataset may be valuable for:

testing preprocessing pipelines,
validating machine learning code,
comparing the behaviour of models trained on synthetic versus real-world datasets,
demonstrating methodological differences between synthetic and real datasets if discussed as a limitation or future research direction.